## Prometheus Exporter / Metrics
##
metrics:
  service:
    annotations:
      service_name: [[.Release.Store.metadata | quote]]
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
