site_name: Helmwave
site_description: 'The helmwave`s docs'
site_author: 'Dmitriy Zhilyaev'
docs_dir: docs/
repo_name: 'helmwave/helmwave'
repo_url: 'https://github.com/helmwave/helmwave'
nav:
  - Home: index.md
  - install.md
  - quick.md
  - Configuration:
    - configuration/tags.md
    - configuration/store.md
    - configuration/full.md
  - anno.md
  - cookbooks.md
  - ci.md

theme:
  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.png
