site_name: Helmwave
site_description: "The helmwave`s docs"
site_author: "Dmitrii Zhiliaev"
docs_dir: docs/
repo_name: "helmwave/helmwave"
repo_url: "https://github.com/helmwave/helmwave"
edit_uri: "https://github.com/helmwave/docs/edit/main/docs/"
site_url: "https://docs.helmwave.app"
copyright: >
  Copyright © 2020 – 2023 Dmitrii Zhiliaev

nav:
  - Home: index.md

  - Getting started:
      - intro.md
      - install.md
      - 🔰 Quick Start: examples/quick-start/README.md
      - ci.md
      - ide.md
      - pub.md

  - Reference:
      - yaml.md
      - cli.md
      - tpl.md
      - anno.md

  - Examples:
      - examples/quick-start/README.md
      - examples/kubedog/README.md
      - examples/graph/README.md
      - Templating:
          - examples/apps-per-ns/README.md
          - examples/single-app-multi-envs/README.md
          - examples/pass-git-commit/README.md
          - examples/pass-git-tag/README.md
          - examples/built-in-release/README.md
          - examples/store-greeting-hello/README.md
      - examples/tags/README.md
      - examples/umbrella-evil/README.md
      - examples/private-env/README.md
      - examples/lifecycle/README.md
      - OCI:
          - examples/oci-private/README.md
          - examples/oci-public/README.md
      - Repositories:
          - examples/private-github-repo/README.md
          - examples/private-gitlab-repo/README.md
      - Values flags:
          - examples/values-delimiter-flags/README.md
          - examples/values-render-flag/README.md
          - examples/values-strict-flag/README.md
      - Data sources:
          - examples/vault/README.md
          - examples/aws-sm/README.md

plugins:
  - search
  - macros:
      j2_variable_start_string: "⟨⟨"
      j2_variable_end_string: "⟩⟩"
      module_name: lib # lib.py
  - mermaid2
  - include-markdown

theme:
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  favicon: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  custom_dir: docs/overrides
  analytics:
    gtag: G-FTBLK54FKZ
  features:
    - content.code.copy
    - content.action.view

    #    - toc.integrate # right/left side
    - toc.follow
    #
    - navigation.top
    #    - navigation.instant # disable because mermaid is not working
    #    - navigation.indexes # disable because quick-start works not correctly
    #    - navigation.expand
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path # only insiders

    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    - search.share
    - search.highlight

extra:
  ver: 0.29.0
  version:
    provider: mike
    default: latest
  analytics:
    provider: google
    property: G-FTBLK54FKZ
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/diamon/helmwave
    - icon: fontawesome/brands/github
      link: https://github.com/helmwave
    - icon: fontawesome/brands/telegram
      link: https://t.me/helmwave

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3
      permalink: true
