site_name: Helmwave
site_description: 'The helmwave`s docs'
site_author: 'Dmitriy Zhilyaev'
docs_dir: docs/
repo_name: 'helmwave/helmwave'
repo_url: 'https://github.com/helmwave/helmwave'
nav:
  - Home: index.md
  - install.md
  - examples/quick-start/README.md
  - Configuration:
    - configuration/tags.md
    - configuration/store.md
    - configuration/full.md
  - tpl.md
  - Examples:
      - 'Passing image.tag': examples/CI_COMMIT_TAG/README.md
      - 'Passing gitCommit': examples/CI_COMMIT_SHORT_SHA/README.md
      - 'Multiple environments': examples/CI_ENVIRONMENT_NAME/README.md
      - 'Use depends_on': examples/depends_on/README.md
  - anno.md
  - cookbooks.md
  - cli.md
  - ci.md

plugins:
  - search
  - mermaid2
  - include-markdown

theme:
  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  favicon: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
