site_name: Helmwave
site_description: 'A docs helmwave'
site_author: 'Dmitriy Zhilyaev'
docs_dir: docs/
repo_name: 'helmwave/helmwave'
repo_url: 'https://github.com/helmwave/helmwave'
nav:
  - Home: index.md
  - install.md
  - Configuration:
      - configuration/tags.md
      - configuration/store.md
      - configuration/full.md
  - Annotations: anno.md

theme:
  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.png
