site_name: Helmwave
site_description: 'The helmwave`s docs'
site_author: 'Dmitriy Zhilyaev'
docs_dir: docs/
repo_name: 'helmwave/helmwave'
repo_url: 'https://github.com/helmwave/helmwave'
edit_uri: 'https://github.com/helmwave/helmwave.github.io/edit/main/docs/'
site_url: 'https://helmwave.github.io'
copyright: Copyright © 2020 - 2021 Dmitriy Zhilyaev


nav:
  - Home: index.md

  - Getting started:
      - intro.md
      - install.md
      - ci.md

  - Reference:
      - cli.md
      - tpl.md
      - anno.md
      - yaml.md

  - Examples:
      - examples/index.md

plugins:
  - search
  - mermaid2
  - include-markdown

theme:
  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  favicon: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  custom_dir: docs/overrides
  analytics:
    gtag: G-FTBLK54FKZ
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.share

extra:
  version:
    provider: mike
    default: latest
    analytics:
      provider: google
      property: G-FTBLK54FKZ

  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/diamon/helmwave
    - icon: fontawesome/brands/github
      link: https://github.com/helmwave
    - icon: fontawesome/brands/telegram
      link: https://t.me/helmwave

markdown_extensions:
  - admonition
  - pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid
