site_name: Helmwave
site_description: 'The helmwave`s docs'
site_author: 'Dmitriy Zhilyaev'
docs_dir: docs/
repo_name: 'helmwave/helmwave'
repo_url: 'https://github.com/helmwave/helmwave'
edit_uri: 'https://github.com/helmwave/docs/edit/main/docs/'
site_url: 'https://helmwave.github.io'
copyright: Copyright © 2020 - 2022 Dmitriy Zhilyaev


nav:
  - Home: index.md

  - Getting started:
      - intro.md
      - install.md
      - ci.md
      - pub.md

  - Reference:
      - yaml.md
      - cli.md
      - tpl.md
      - anno.md


  - Examples:
      - examples/quick-start/README.md
      - examples/apps-per-ns/README.md
      - examples/pass-git-tag/README.md
      - examples/pass-git-commit/README.md
      - examples/single-app-multi-envs/README.md
      - examples/oci/README.md
      - examples/aws-sm/README.md
      - examples/vault/README.md
      - examples/kubedog/README.md
      - examples/private-github-repo/README.md
      - Store: examples/store-greeting-hello/README.md
      - examples/built-in-release/README.md

plugins:
  - search
  - mermaid2
  - include-markdown

theme:
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  favicon: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  custom_dir: docs/overrides
  analytics:
    gtag: G-FTBLK54FKZ
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.share

extra:
  ver: 0.19.3
  version:
    provider: mike
    default: latest
  analytics:
    provider: google
    property: G-FTBLK54FKZ

  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/diamon/helmwave
    - icon: fontawesome/brands/github
      link: https://github.com/helmwave
    - icon: fontawesome/brands/telegram
      link: https://t.me/helmwave

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
