site_name: Helmwave
site_description: "The helmwave`s docs"
site_author: "Dmitriy Zhilyaev"
docs_dir: docs/
repo_name: "helmwave/helmwave"
repo_url: "https://github.com/helmwave/helmwave"
edit_uri: "https://github.com/helmwave/docs/edit/main/docs/"
site_url: "https://helmwave.github.io"
copyright: >
  Copyright © 2020 – 2023 Dmitrii Zhiliaev –
  <a href="#__consent">Change cookie settings</a>


nav:
  - Home: index.md

  - Getting started:
      - intro.md
      - install.md
      - 🔰 Quick Start: examples/quick-start/README.md
      - ci.md
      - ide.md
      - pub.md

  - Reference:
      - yaml.md
      - cli.md
      - tpl.md
      - anno.md

  - Examples:
      - examples/quick-start/README.md
      - examples/apps-per-ns/README.md
      - examples/aws-sm/README.md
      - examples/built-in-release/README.md
      - examples/hate-umbrella/README.md
      - examples/kubedog/README.md
      - examples/oci-private/README.md
      - examples/oci-public/README.md
      - examples/pass-git-commit/README.md
      - examples/pass-git-tag/README.md
      - examples/private-github-repo/README.md
      - examples/private-gitlab-repo/README.md
      - examples/single-app-multi-envs/README.md
      - Store: examples/store-greeting-hello/README.md
      - examples/values-delimiter-flags/README.md
      - examples/values-render-flag/README.md
      - examples/values-strict-flag/README.md
      - examples/vault/README.md

plugins:
  - search
  - mermaid2
  - include-markdown

theme:
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  name: material
  logo: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  favicon: https://raw.githubusercontent.com/helmwave/logo/main/logo.ico
  custom_dir: docs/overrides
  analytics:
    gtag: G-FTBLK54FKZ
  features:
    - content.code.copy
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.share

extra:
  version:
    provider: mike
    default: latest
  analytics:
    provider: google
    property: G-FTBLK54FKZ
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/diamon/helmwave
    - icon: fontawesome/brands/github
      link: https://github.com/helmwave
    - icon: fontawesome/brands/telegram
      link: https://t.me/helmwave

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
