#commonAnnotations:
#  helmwave.dev/show-service-messages: "true"
#  helmwave.dev/show-logs-only-for-containers: "nginx"

podAnnotations:
  datetime: {{ now }}
  blame: {{ env "USER" }}

replicaCount: 1

auth:
  enabled: false

master:
  persistence:
    enabled: false

replica:
  persistence:
    enabled: false
