# Uncommented it if you need
commonAnnotations:
  helmwave.app/show-service-messages: "true"
  helmwave.app/show-logs-only-for-containers: "redis"

podAnnotations:
  datetime: {{ now }}
  blame: {{ env "USER" }}

replicaCount: 1

auth:
  enabled: false

master:
  persistence:
    enabled: false

replica:
  persistence:
    enabled: false
