helmwave:
  stage: deploy
  image:
    name: ghcr.io/helmwave/helmwave:⟨⟨ ver ⟩⟩
    entrypoint: [""]
  before_script:
    - printenv | grep HELMWAVE
  script:
    - helmwave yml
    - helmwave build
    - helmwave up
  artifacts:
    paths:
      - .helmwave
    expire_in: 2 weeks