apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: world-hello
    patch: |
      - op: replace
        path: /spec/template/spec/priorityClassName
        value: high
        
