name: Publish branch
on:
  push:
    branches:
      - "*.*.x"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Mike with updating aliases
        if: ${{ github.event.created }}
        run: |
          mike deploy --push --force --update-aliases ${{ steps.extract_branch.outputs.branch }} latest --rebase

      - name: Mike
        if: ${{ !github.event.created }}
        run: |
          mike deploy --force --push ${{ steps.extract_branch.outputs.branch }}
