name: Publish branch
on:
  push:
    branches:
      - "*.*.x"
  workflow_dispatch:
    inputs:
      update_aliases:
        description: Whether to update mike aliases
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: helmwave/setup-action@v0.3.0
        with:
          version: '0.33.0'

      - run: helmwave schema > schema.json

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Mike with updating aliases
        if: ${{ github.event.created || inputs.update_aliases }}
        run: |
          mike deploy --push --force --update-aliases ${{ github.ref_name }} latest --rebase

      - name: Mike
        if: ${{ !github.event.created && !inputs.update_aliases }}
        run: |
          mike deploy --force --push ${{ github.ref_name }}
